import type { ToolDefinition } from './types';

export const TOOLS: ToolDefinition[] = [
  {
    id: 'move-pixels',
    name: 'Move Selected Pixels',
    icon: 'tool-move-symbolic.svg',
    shortcut: 'M',
    status: 'Drag to move the pixels in the selected area.',
  },
  {
    id: 'move-selection',
    name: 'Move Selection',
    icon: 'tool-move-selection-symbolic.svg',
    shortcut: 'M',
    status: 'Drag to move the selection outline.',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    icon: 'tool-zoom-symbolic.svg',
    shortcut: 'Z',
    status: 'Click to zoom in. Hold Alt and click to zoom out.',
  },
  { id: 'pan', name: 'Pan', icon: 'tool-pan-symbolic.svg', shortcut: 'H', status: 'Drag to pan around the image.' },
  {
    id: 'rectangle-select',
    name: 'Rectangle Select',
    icon: 'tool-select-rectangle-symbolic.svg',
    shortcut: 'S',
    status: 'Drag to select or resize with the handles. Hold Shift for a square; click once to deselect.',
  },
  {
    id: 'ellipse-select',
    name: 'Ellipse Select',
    icon: 'tool-select-ellipse-symbolic.svg',
    shortcut: 'S',
    status: 'Drag to select or resize with the handles. Hold Shift for a circle; click once to deselect.',
  },
  {
    id: 'lasso-select',
    name: 'Lasso Select',
    icon: 'tool-select-lasso-symbolic.svg',
    shortcut: 'S',
    status: 'Draw a freeform selection.',
  },
  {
    id: 'magic-wand',
    name: 'Magic Wand Select',
    icon: 'tool-select-magicwand-symbolic.svg',
    shortcut: 'S',
    status: 'Select areas of similar color.',
  },
  {
    id: 'paintbrush',
    name: 'Paintbrush',
    icon: 'tool-paintbrush-symbolic.svg',
    shortcut: 'B',
    status: 'Click and drag to draw with the primary color.',
  },
  {
    id: 'pencil',
    name: 'Pencil',
    icon: 'tool-pencil-symbolic.svg',
    shortcut: 'P',
    status: 'Draw one-pixel freehand lines.',
  },
  {
    id: 'eraser',
    name: 'Eraser',
    icon: 'tool-eraser-symbolic.svg',
    shortcut: 'E',
    status: 'Erase pixels from the active layer.',
  },
  {
    id: 'paint-bucket',
    name: 'Paint Bucket',
    icon: 'tool-paintbucket-symbolic.svg',
    shortcut: 'F',
    status: 'Fill a contiguous region with the primary color.',
  },
  {
    id: 'gradient',
    name: 'Gradient',
    icon: 'tool-gradient-symbolic.svg',
    shortcut: 'G',
    status: 'Click and drag to draw a color gradient.',
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    icon: 'tool-colorpicker-symbolic.svg',
    shortcut: 'K',
    status: 'Pick a color from the image.',
  },
  {
    id: 'text',
    name: 'Text',
    icon: 'tool-text-symbolic.svg',
    shortcut: 'T',
    status: 'Click to place text on the active layer.',
  },
  {
    id: 'line',
    name: 'Line / Curve',
    icon: 'tool-line-symbolic.svg',
    shortcut: 'O',
    status: 'Draw a line, then drag its handles or click the path to shape a curve.',
  },
  {
    id: 'rectangle',
    name: 'Rectangle',
    icon: 'tool-rectangle-symbolic.svg',
    shortcut: 'O',
    status: 'Click and drag to draw a rectangle.',
  },
  {
    id: 'rounded-rectangle',
    name: 'Rounded Rectangle',
    icon: 'tool-rectangle-rounded-symbolic.svg',
    shortcut: 'O',
    status: 'Click and drag to draw a rounded rectangle.',
  },
  {
    id: 'ellipse',
    name: 'Ellipse',
    icon: 'tool-ellipse-symbolic.svg',
    shortcut: 'O',
    status: 'Click and drag to draw an ellipse.',
  },
  {
    id: 'freeform',
    name: 'Freeform Shape',
    icon: 'tool-freeformshape-symbolic.svg',
    shortcut: 'O',
    status: 'Draw a closed freeform shape with the selected fill and outline style.',
  },
  {
    id: 'clone-stamp',
    name: 'Clone Stamp',
    icon: 'tool-clonestamp-symbolic.svg',
    shortcut: 'L',
    status: 'Clone pixels from another part of the image.',
  },
  {
    id: 'recolor',
    name: 'Recolor',
    icon: 'tool-recolor-symbolic.svg',
    shortcut: 'R',
    status: 'Replace one color with another.',
  },
];

export const TOOL_BY_ID = {
  ...Object.fromEntries(TOOLS.map((tool) => [tool.id, tool])),
  'block-brush': {
    id: 'block-brush',
    name: 'Block Brush',
    icon: 'tool-paintbrush-symbolic.svg',
    status: 'Paint continuous hard-edged block strokes.',
    addinId: 'block-brush',
  },
} as Record<ToolDefinition['id'], ToolDefinition>;

export const PALETTE = [
  '#ffffff',
  '#000000',
  '#a0a0a0',
  '#808080',
  '#404040',
  '#303030',
  '#ff0000',
  '#ff7f7f',
  '#ff6a00',
  '#ffb27f',
  '#ffd800',
  '#ffe97f',
  '#b6ff00',
  '#daff7f',
  '#4cff00',
  '#a5ff7f',
  '#00ff21',
  '#7fff8e',
  '#00ff90',
  '#7fffc5',
  '#00ffff',
  '#7fffff',
  '#0094ff',
  '#7fc9ff',
  '#0026ff',
  '#7f92ff',
  '#4800ff',
  '#a17fff',
  '#b200ff',
  '#d67fff',
  '#ff00dc',
  '#ff7fed',
  '#ff006e',
  '#ff7fb6',
];
