// Generated by scripts/generate-i18n-catalogs.mjs. Do not edit by hand.
export const SUPPORTED_LOCALES = [
  {
    "code": "en",
    "name": "English",
    "direction": "ltr",
    "coverage": 100,
    "preserved": false
  },
  {
    "code": "ar",
    "name": "العربية",
    "direction": "rtl",
    "coverage": 96.1,
    "preserved": false
  },
  {
    "code": "cs",
    "name": "čeština",
    "direction": "ltr",
    "coverage": 100,
    "preserved": false
  },
  {
    "code": "de",
    "name": "Deutsch",
    "direction": "ltr",
    "coverage": 97.1,
    "preserved": false
  },
  {
    "code": "el",
    "name": "Ελληνικά",
    "direction": "ltr",
    "coverage": 94.4,
    "preserved": false
  },
  {
    "code": "en-CA",
    "name": "English (Canada)",
    "direction": "ltr",
    "coverage": 98.4,
    "preserved": false
  },
  {
    "code": "en-GB",
    "name": "English (United Kingdom)",
    "direction": "ltr",
    "coverage": 100,
    "preserved": false
  },
  {
    "code": "es",
    "name": "español",
    "direction": "ltr",
    "coverage": 97.6,
    "preserved": false
  },
  {
    "code": "eu",
    "name": "euskara",
    "direction": "ltr",
    "coverage": 94.4,
    "preserved": false
  },
  {
    "code": "fr",
    "name": "français",
    "direction": "ltr",
    "coverage": 97.6,
    "preserved": false
  },
  {
    "code": "ga",
    "name": "Gaeilge",
    "direction": "ltr",
    "coverage": 100,
    "preserved": false
  },
  {
    "code": "he",
    "name": "עברית",
    "direction": "rtl",
    "coverage": 70.2,
    "preserved": true
  },
  {
    "code": "hr",
    "name": "hrvatski",
    "direction": "ltr",
    "coverage": 99.4,
    "preserved": false
  },
  {
    "code": "id",
    "name": "Bahasa Indonesia",
    "direction": "ltr",
    "coverage": 99.4,
    "preserved": false
  },
  {
    "code": "it",
    "name": "italiano",
    "direction": "ltr",
    "coverage": 94.4,
    "preserved": false
  },
  {
    "code": "kk",
    "name": "қазақ тілі",
    "direction": "ltr",
    "coverage": 97.1,
    "preserved": false
  },
  {
    "code": "ko",
    "name": "한국어",
    "direction": "ltr",
    "coverage": 97.1,
    "preserved": false
  },
  {
    "code": "nl",
    "name": "Nederlands",
    "direction": "ltr",
    "coverage": 100,
    "preserved": false
  },
  {
    "code": "pl",
    "name": "polski",
    "direction": "ltr",
    "coverage": 100,
    "preserved": false
  },
  {
    "code": "pt",
    "name": "português",
    "direction": "ltr",
    "coverage": 99.4,
    "preserved": false
  },
  {
    "code": "pt-BR",
    "name": "português (Brasil)",
    "direction": "ltr",
    "coverage": 94.4,
    "preserved": false
  },
  {
    "code": "ru",
    "name": "русский",
    "direction": "ltr",
    "coverage": 100,
    "preserved": false
  },
  {
    "code": "sl",
    "name": "slovenščina",
    "direction": "ltr",
    "coverage": 100,
    "preserved": false
  },
  {
    "code": "sv",
    "name": "svenska",
    "direction": "ltr",
    "coverage": 100,
    "preserved": false
  },
  {
    "code": "ta",
    "name": "தமிழ்",
    "direction": "ltr",
    "coverage": 90.2,
    "preserved": false
  },
  {
    "code": "tr",
    "name": "Türkçe",
    "direction": "ltr",
    "coverage": 100,
    "preserved": false
  },
  {
    "code": "uk",
    "name": "українська",
    "direction": "ltr",
    "coverage": 94.4,
    "preserved": false
  },
  {
    "code": "vi",
    "name": "Tiếng Việt",
    "direction": "ltr",
    "coverage": 94.4,
    "preserved": false
  },
  {
    "code": "zh-CN",
    "name": "简体中文",
    "direction": "ltr",
    "coverage": 90.5,
    "preserved": false
  },
  {
    "code": "zh-TW",
    "name": "繁體中文",
    "direction": "ltr",
    "coverage": 94.5,
    "preserved": false
  }
] as const;

export type LocaleCode = (typeof SUPPORTED_LOCALES)[number]['code'];

export const SEO_LOCALE_CODES = ["en","fr","de","ar","he"] as const;

export const I18N_CATALOG_SUMMARY = {
  "threshold": 90,
  "templateMessages": 621,
  "upstreamCatalogs": 73,
  "qualifyingCatalogs": 28,
  "shippedCatalogs": 29
} as const;

export const localeLoaders = {
  "ar": () => import("./locales/ar.json").then((module) => module.default),
  "cs": () => import("./locales/cs.json").then((module) => module.default),
  "de": () => import("./locales/de.json").then((module) => module.default),
  "el": () => import("./locales/el.json").then((module) => module.default),
  "en-CA": () => import("./locales/en-CA.json").then((module) => module.default),
  "en-GB": () => import("./locales/en-GB.json").then((module) => module.default),
  "es": () => import("./locales/es.json").then((module) => module.default),
  "eu": () => import("./locales/eu.json").then((module) => module.default),
  "fr": () => import("./locales/fr.json").then((module) => module.default),
  "ga": () => import("./locales/ga.json").then((module) => module.default),
  "he": () => import("./locales/he.json").then((module) => module.default),
  "hr": () => import("./locales/hr.json").then((module) => module.default),
  "id": () => import("./locales/id.json").then((module) => module.default),
  "it": () => import("./locales/it.json").then((module) => module.default),
  "kk": () => import("./locales/kk.json").then((module) => module.default),
  "ko": () => import("./locales/ko.json").then((module) => module.default),
  "nl": () => import("./locales/nl.json").then((module) => module.default),
  "pl": () => import("./locales/pl.json").then((module) => module.default),
  "pt": () => import("./locales/pt.json").then((module) => module.default),
  "pt-BR": () => import("./locales/pt-BR.json").then((module) => module.default),
  "ru": () => import("./locales/ru.json").then((module) => module.default),
  "sl": () => import("./locales/sl.json").then((module) => module.default),
  "sv": () => import("./locales/sv.json").then((module) => module.default),
  "ta": () => import("./locales/ta.json").then((module) => module.default),
  "tr": () => import("./locales/tr.json").then((module) => module.default),
  "uk": () => import("./locales/uk.json").then((module) => module.default),
  "vi": () => import("./locales/vi.json").then((module) => module.default),
  "zh-CN": () => import("./locales/zh-CN.json").then((module) => module.default),
  "zh-TW": () => import("./locales/zh-TW.json").then((module) => module.default),
} satisfies Record<Exclude<LocaleCode, 'en'>, () => Promise<Record<string, string>>>;
